name: build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: oreradar-fabric-project/fabric-template
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: make gradlew executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: oreradar-fabric-project/fabric-template/build/libs/
